[package]
name = "zap"
version = "0.0.1"
authors = ["Daniel Oltmanns <daniel.oltmanns@outlook.de>"]
description = "Ligthing fast web framework for rust"
keywords = ["web-framework", "http", "efficiency"]

[dependencies]
bytes = "0.4"
futures = "0.1.11"
httparse = "1.1.2"
log = "0.3.6"
net2 = "0.2"
time = "0.1"
tokio-core = "0.1.0"
tokio-io = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
